// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// nbinomGLM
Rcpp::List nbinomGLM(Rcpp::NumericMatrix x, Rcpp::NumericMatrix Y, Rcpp::NumericVector size, Rcpp::NumericMatrix weights, Rcpp::NumericMatrix offset, double sigma2, double S2, Rcpp::NumericVector no_shrink, Rcpp::NumericVector shrink, Rcpp::NumericVector cnst);
RcppExport SEXP _apeglm_nbinomGLM(SEXP xSEXP, SEXP YSEXP, SEXP sizeSEXP, SEXP weightsSEXP, SEXP offsetSEXP, SEXP sigma2SEXP, SEXP S2SEXP, SEXP no_shrinkSEXP, SEXP shrinkSEXP, SEXP cnstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type S2(S2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type no_shrink(no_shrinkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type shrink(shrinkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type cnst(cnstSEXP);
    rcpp_result_gen = Rcpp::wrap(nbinomGLM(x, Y, size, weights, offset, sigma2, S2, no_shrink, shrink, cnst));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_apeglm_nbinomGLM", (DL_FUNC) &_apeglm_nbinomGLM, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_apeglm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
